post http://localhost:3000/api/user/login/
Content-Type: application/json

{
"email": "charles@gmail.com",
"password": "eLamp2021"
}

###
post http://localhost:3000/api/message/
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjY5NDMzOTEsImV4cCI6MTYyNzAyOTc5MX0.ev4H6jZHhDSnfI5LgDJjKcCcOGr_5h9MaBa7SeySR7w

{
"title": "Publication Test Micro 7",
"content": "Je ne m'arrête jamais !"
}

###
delete http://localhost:3000/api/message/8/
Content-Type: application/json

{

}

###
put http://localhost:3000/api/message/9/
Content-Type: application/json

{
    "title": "Changement de titre"
}
