//Test API routes USERS

post http://localhost:3000/api/user/login/
Content-Type: application/json

{
"email": "charlesdegalles@england.co.uk",
"password": "England1948"
}

###
post http://localhost:3000/api/user/login/
Content-Type: application/json

{
"email": "charles.helliet@gmail.com",
"password": "eLamp2021"
}

###
get http://localhost:3000/api/user/profile/2/
Content-Type: application/json

{

}

###
put http://localhost:3000/api/user/profile/3/
Content-Type: application/json

{
    "bio": "Alessandro Nesta, né le 19 mars 1976 à Rome, est un ancien footballeur international italien désormais reconverti entraîneur. Considéré comme l'un des meilleurs défenseurs centraux de son époque, il est double vainqueur de la Ligue des champions avec l'AC Milan et a remporté la Coupe du monde 2006."
}

###
delete http://localhost:3000/api/user/profile/15/
Content-Type: application/json

{
    
}

###
get http://localhost:3000/api/user/profile/
Content-Type: application/json

{
    
}

//Test API routes MESSAGES

###
post http://localhost:3000/api/message/
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjk5ODkyMDQsImV4cCI6MTYzMDA3NTYwNH0.Z03RixniD9_JVGmJkkskgE0dJ9qavqT_ybyiTtE1oD0

{
"title": "Publication du Prince de Galles numéro 2",
"content": "Je ne m'arrête jamais !"
}

###
delete http://localhost:3000/api/message/8/
Content-Type: application/json

{

}

###
put http://localhost:3000/api/message/9/
Content-Type: application/json

{
    "title": "Changement de titre",
    "content": "Je sais faire une requête PUT!"
}

###
get http://localhost:3000/api/message/
Content-Type: application/json

{
    
}